/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ProfessorPanel;

import Business.Business;
import Courses.Course;
import Students.Student;
import UserAccount.UserAccount;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankithreddy
 */
public class ManageAccountPanel extends javax.swing.JPanel {
    
    private Business business;
    private UserAccount useraccount;
    /**
     * Creates new form ManageStudents
     */
    public ManageAccountPanel() {
        initComponents();
    }

    public ManageAccountPanel(Business business, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.business = business;
        this.useraccount = useraccount;
       System.out.println("i AM IN constructor of MANAGE ACCOUNT : ");

        populateTbl();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void populateTbl (){
        DefaultTableModel model=(DefaultTableModel)coursesTbl.getModel();
        model.setRowCount(0);
        int revenue=0;
     //   System.out.println("i AM IN MANAGE ACCOUNT : "+ this.useraccount.getProfessor().getProfStudentList().get(0).getName());
        for(Student s:this.useraccount.getProfessor().getProfStudentList()){
            for(Course c:s.getTranscript().getCoursecatlogue().getCourseList()){
                if(c.getProfessor().getProfessorName().equals(this.useraccount.getProfessor().getProfessorName())){
                     revenue+=c.getTotalCoursePrice();
                }
            }
            
        }
        this.useraccount.getProfessor().setRevenue(revenue);
       
        for (Course c : this.useraccount.getProfessor().getProfCourseList()){
            Object[] row=new Object[3];
            row[0]=c;
           row[1]=this.useraccount.getProfessor().getProfStudentList().size();
          row[2]= this.useraccount.getProfessor().getRevenue();
            
            model.addRow(row);
        }
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        coursesTbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));

        coursesTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Courses", "No. of Students enrolled", "Revenue"
            }
        ));
        jScrollPane1.setViewportView(coursesTbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable coursesTbl;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
