/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Business.Business;
import Professor.Professor;
import Role.CertifierRole;
import Role.ProfessorRole;
import Role.Role;
import Role.StudentRole;
import Students.Student;
import UserAccount.UserAccount;
import UserAccount.UserAccountDirectory;
import javax.swing.JOptionPane;

/**
 *
 * @author ankithreddy
 */
public class SignupJPanel extends javax.swing.JPanel {
    
        private Business business;
        private UserAccount useraccount;
        public UserAccountDirectory userAccountDirectory;
        public MainJFrame mj;


    /**
     * Creates new form SIgnupPanel
     */
    public SignupJPanel() {
        initComponents();
//         this.business = Business.getInstance();
//          this.userAccountDirectory = business.getUserAccountDirectory();
//        populateComboBox ();
    }
    
     public SignupJPanel(Business business, UserAccount useraccount){
                initComponents();
                this.setVisible(true);
                this.business = business;
                this.userAccountDirectory = business.getUserAccountDirectory();
                populateComboBox ();


                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void populateComboBox (){
         rolesCBox.removeAllItems();
        for (String rolename : Role.getAllRoles()) {
            rolesCBox.addItem(rolename);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        PasswordTxt = new javax.swing.JTextField();
        countryTxt = new javax.swing.JTextField();
        rolesCBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        signupBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Country");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");

        signupBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(255, 255, 255));
        signupBtn.setText("SIGNUP");
        signupBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        signupBtn.setContentAreaFilled(false);
        signupBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(countryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(216, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rolesCBox, 0, 140, Short.MAX_VALUE)
                            .addComponent(usernameTxt)
                            .addComponent(PasswordTxt)
                            .addComponent(emailTxt))
                        .addGap(32, 216, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(246, 246, 246))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(rolesCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PasswordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(countryTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(signupBtn)
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        // TODO add your handling code here:
        
        
        String username = usernameTxt.getText();
        String password = PasswordTxt.getText();
        String country = countryTxt.getText();
        String email = emailTxt.getText();
        
        if(username.equals("")||password.equals("")||country.equals("")||email.equals("")){
            JOptionPane.showMessageDialog(null, "please fill all details to signup ");
        } else {
        
        UserAccountDirectory ua = this.business.getUserAccountDirectory();
        
        if(this.business.getUserAccountDirectory().findByUserName(username)!=null ){
            JOptionPane.showMessageDialog(null, "Sorry credentials are taken.");
            System.out.println("i am checking if account exists ");
        }
        else {

        if (rolesCBox.getSelectedItem().equals("Student")){
            
            UserAccount user = this.business.getUserAccountDirectory().createUserAccount(usernameTxt.getText(), PasswordTxt.getText(), new StudentRole());
            Student student = this.business.getStudentDirectory().createStudent(usernameTxt.getText(), countryTxt.getText(), emailTxt.getText());
            user.setStudent(student);
            //this.business.getStudentDirectory().getStudentlist().add(student);
            System.out.println("student created in : "+ student.getName());
            JOptionPane.showMessageDialog(null, "your student profile has been created");
            usernameTxt.setText("");
            PasswordTxt.setText("");
            countryTxt.setText("");
            emailTxt.setText("");
        } else if (rolesCBox.getSelectedItem().equals("Professor")) {
          UserAccount user=  this.business.getUserAccountDirectory().createUserAccount(usernameTxt.getText(), PasswordTxt.getText(), new ProfessorRole());
          Professor professor =this.business.getProfessorDirectory().createProfessor(usernameTxt.getText(),countryTxt.getText(),emailTxt.getText());
          user.setProfessor(professor);
          System.out.println("Professor created in : "+ professor.getProfessorName());

           JOptionPane.showMessageDialog(null, "your Professor profile has been created"); 
           usernameTxt.setText("");
            PasswordTxt.setText("");
            countryTxt.setText("");
            emailTxt.setText("");
        
        }
        } 
        }
        
    }//GEN-LAST:event_signupBtnActionPerformed

    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PasswordTxt;
    private javax.swing.JTextField countryTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> rolesCBox;
    private javax.swing.JButton signupBtn;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
