/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.StudentPanel;

import Business.Business;
import Courses.Course;
import UserAccount.UserAccount;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ankithreddy
 */
public class ManangeStuAccountPanel extends javax.swing.JPanel {
Business business;
UserAccount useraccount;
    /**
     * Creates new form ManangeStuAccountPanel
     */
    public ManangeStuAccountPanel(Business business,UserAccount useraccount) {
        initComponents();
        this.business=business;
        this.useraccount=useraccount;
        populatetable();

    }
    public void populatetable(){
         DefaultTableModel tableModel=(DefaultTableModel)jtable.getModel();
                 tableModel.setRowCount(0);

        for(Course c:this.useraccount.getStudent().getTranscript().getCoursecatlogue().getCourseList()){
             Object[] row = new Object[4];
                  row[0]=c;
                  row[1]=c.getReputationIndex();
                  row[2]=c.getProfessor().getProfessorName();
                  row[3]=c.getProfessor().getProfessorRating();
            tableModel.addRow(row);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        repIndexBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course", "Reputation Index", "Professor", "Professor Rating"
            }
        ));
        jtable.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jtableHierarchyChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);

        jButton1.setText("Rate Professor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        repIndexBtn.setText("Course Reputation Index");
        repIndexBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repIndexBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(repIndexBtn))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repIndexBtn))
                .addContainerGap(95, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtableHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jtableHierarchyChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jtableHierarchyChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow=jtable.getSelectedRow();
        
        if(selectedRow >=0){
           int profrating =Integer.parseInt( (jtable.getValueAt(selectedRow, 3)).toString());
           int rating=Integer.parseInt(jTextField1.getText());
           int average=(profrating+rating)/2;
           
           Course c=this.useraccount.getStudent().getTranscript().searchintranscript(jtable.getValueAt(selectedRow, 0).toString());
           c.getProfessor().setProfessorRating(average);
            populatetable();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void repIndexBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repIndexBtnActionPerformed
        // TODO add your handling code here:
                int selectedRow=jtable.getSelectedRow();
                
         if(selectedRow >=0){
           int repindex =Integer.parseInt( (jtable.getValueAt(selectedRow, 1)).toString());
           int index=Integer.parseInt(jTextField2.getText());
           int average=(repindex+index)/2;
           
           Course c=this.useraccount.getStudent().getTranscript().searchintranscript(jtable.getValueAt(selectedRow, 0).toString());
           c.setReputationIndex(average);
            populatetable();
        }

    }//GEN-LAST:event_repIndexBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable jtable;
    private javax.swing.JButton repIndexBtn;
    // End of variables declaration//GEN-END:variables
}
